language: node_js
node_js:
  - "12"

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules

  install:
    - npm install claudia -g
    - travis_retry npm install

  script:
    - claudia generate-serverless-express-proxy --express-module app
    - claudia create --handler lambda.handler --deploy-proxy-api --region ap-southeast-1

environments:
  - &MAIN_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Lambda Testing"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="test"
        - STAGE_NAME=main
        - *MAIN_ENV
